package NamaZodiak.SubmissionDicoding.AndroidPemula;

import java.util.ArrayList;

public class DataZodiak {
        /*
 * 0: Nama Zodiak
 * 1: Asal
 * 2: Deskripsi
 * 3: Photo resource
 */

        // Data source: https://moondoggiesmusic.com/nama-nama-zodiak/
        public static String[][] data = new String[][] {
                {
                        "Capricorn",
                        "(21 Desember – 19 Januari)",
                        "https://moondoggiesmusic.com/wp-content/uploads/2019/06/Zodiak-Capricorn-21-Desember-%E2%80%93-19-Januari.png",
                        "Bagi Anda yang lahir antara tanggal 21 Desember hingga tanggal 19 Januari berarti zodiak Anda termasuk ke dalam jenis Capricorn. Beberapa sifat yang cukup menonjol dari orang yang mempunyai zodiak Capricorn yaitu mengutamakan reputasi, kesuksesan, jabatan, loyal, status, bijaksana, takut akan hambatan, bertanggung jawab, pesimis, rendah diri, berfikir sempit dan memiliki rasa khawatir yang berlebihan.\n\n" + "Selain itu, sifatnya cukup pendiam, materialis, suka memerintah, rajin, ambisius, mempunyai gengsi yang tinggi dan suka memperalat orang lain. Zodiak yang disimbolkan dengan kambing jantan ini selalu mempunyai keinginan untuk mencapai segala sesuatu yang diinginkan.\n\n" + "Keinginan yang kuat mereka biasanya dipakai untuk meraih atau mencapai rasa aman. Mereka juga sangat mantap dalam mengambil suatu langkah seperti seekor kambing gunung. Keyakinan dan kapasitas kerja yang dimiliki sangatlah besar.\n\n" + "Individu yang berzodiak Capricorn jarang sekali meminta bantuan orang lain dan mempunyai rasa kewaspadaan. Jadi, segala sesuatunya lebih mereka sukai untuk mengerjakannya sendiri. Karakternya sangat sensitif dan sangat memerlukan penghargaan maupun pengakuan dari orang lain..\n\n" +
                        "Capricorn merupakan individu yang pantang menyerah dan memiliki kemantapan yang tinggi untuk meraih tujuannya."

                },
                {
                        "Aquarius",
                        "(20 Januari – 18 Februari)",
                        "https://moondoggiesmusic.com/wp-content/uploads/2019/06/Zodiak-Aquarius-20-Januari-%E2%80%93-18-Februari.png",
                        "Orang-orang yang tanggal kelahirannya 20 Januari sampai tanggal 18 Febuari adalah pemilik zodiak Aquarius. Pada umumnya orang yang mempunyai zodiak Aquarius sifatnya spontan, cinta petualangan, berjiwa sosial tinggi, progresif, ingin memberikan manfaat bagi orang-orang yang ada disekitarnya dan jiwa kemanusiaannya tinggi.\n\n" +
                        "Individu yang berzodiak Aquarius juga radikal, suka memberontak, tidak konsisten dan suka membantah. Tetapi pembawaannya tenang, cerdas, kreatif, obyektif atau tidak memihak kepada siapapun, inovatif serta mudah mengerti.\n\n" + "Aquarius cenderung agak individualistik, progresif dalam cara berpikir dan juga enggan mengikuti keramaian. Beberapa orang yang berzodiak Aquarius sudah berhasil membuktikan bisa menjadi seorang pemimpin walaupun mereka pada dasarnya tidak terlalu antusias menjadi seorang pemimpin.\n\n" + "Meskipun dari luar nampak tenang, di dalam bekerja mereka selalu serius dan di dalam hati mereka sebenarnya ada perasaan gugup dan sangat takut. Pemilik zodiak Aquarius menyukai barang-barang yang sifatnya mewah, namun tidak serakah.\n\n" + "Mereka tidak menyukai aturan kuno dan adat istiadat yang ada di dalam keluarganya. Berbagai aturan yang ada cenderung mereka langgar. Aquarius mampu menyelesaikan masalah yang dihadapi karena mereka bisa keluar dari keadaan dilema.\n\n" +
                        "Terhadap hal-hal yang besar dan sangat manusiawi mereka cukup peduli. Aquarius merupakan pribadi yang senang atau lebih menyukai menyendiri. Memerlukan banyak waktu untuk mengenal pemilik zodiak ini. Mereka akan terbuka hanya terhadap orang yang memang mereka percayai saja. Jadi, tidak sembarangan orang bisa dekat dengan pemilik zodiak Aquarius."
                },
                {
                        "Pisces",
                        "(19 Februari – 20 Maret)",
                        "https://moondoggiesmusic.com/wp-content/uploads/2019/06/Zodiak-Pisces-19-Februari-%E2%80%93-20-Maret.png",
                        "Orang yang terlahir pada tanggal 19 Febuari sampai tanggal 20 Maret masuk dalam kategori zodiak Pisces. Lambang dari zodiak Pisces yaitu berupa dua ekor ikan. Pada umumnya sifat Pisces yaitu romantis, agak manja, memiliki kegemaran di bidang seni, religius, mengalah, setia, selalu memegang teguh kepercayaan, mendengar kata hati, terkadang merasa bingung, risau, mudah kecewa serta tidak konsisten. \n\n" +
                        "Tetapi Pisces mempunyai sisi manusiawi yang besar, simple, suka berimajinasi dan penuh cinta. Pisces cenderung sensitif dan merupakan kaum yang ekstrim. Segala macam hal ingin mereka laksanakan dengan baik tetapi untuk dikerjakan sulit sekali.\n\n" + "Hal ini karena mereka juga harus selalu mendengarkan kata hati terkait hal yang benar maupun salah. Pemilik zodiak Pisces ini penuh dengan pesona. Memiliki simpati dan sedikit sense humor ketika berhadapan dengan orang lain. Jadi, banyak sekali pertolongan dari orang lain yang mereka terima.\n\n" + "Agar Pisces merasa bahagia, mereka memerlukan suatu wadah untuk mengembangkan bakat yang dimilikinya. Jika terjebak dalam suatu rutinitas, mereka akan merasa frustasi. Terhadap janji-janji yang diberikan oleh orang lain mereka mudah percaya tanpa berpikir panjang.\n\n" + "Zodiak Pisces pandai sekali memainkan perasaan. Mereka bisa menjadi pribadi yang sangat sensitif terhadap apa yang orang lain rasakan. Selain itu mereka bisa menjadi mudah marah tanpa adanya alasan yang jelas sehingga orang lain menjadi sulit menebak perasaan mereka. Pisces juga mempunyai kepandaian dalam hal membujuk.\n\n" + "Mereka akan merasa senang jika pekerjaan yang sudah dilakukannya dihargai oleh orang lain. Jika apa yang mereka kerjakan tidak dihargai, maka untuk kesempatan berikutnya mereka tidak akan mengerjakan tugasnya atau pekerjaannya dengan benar.\n\n" + "Pisces menyenangi berbagai hal yang sifatnya menghibur. Mereka nampak tertutup dan malu-malu, namun pada faktanya tidak demikian. Mereka tidak akan merasa ragu untuk ikut mengambil bagian jika merasa nyaman dengan lingkungannya tersebut."

                },
                {
                        "Aries",
                        "(21 Maret – 20 April)",
                        "https://moondoggiesmusic.com/wp-content/uploads/2019/06/Zodiak-Aries-21-Maret-%E2%80%93-20-April.png",
                        "Zodiak Aries merupakan zodiak orang yang lahir pada tanggal 21 Maret sampai tanggal 20 April. Lambang zodiak yang berupa domba atau biri-biri jantan ini masuk ke dalam kategori kardinal atau aktif. Jadi, orang yang berzodiak Aries secara umum memiliki sifat yang berani, suka tantangan, mempunyai daya juang, percaya diri, mengutamakan tindakan serta memiliki inisiatif. \n\n" +
                        "Walaupun demikian zodiak Aries juga mempunyai sifat yang kurang baik yaitu agresif, kurang terencana, agak sombong, agak kasar, terburu-buru yang membuat hasil kerjanya tidak sempurna. Tetapi, seluruh kekurangan tersebut sering tertutupi oleh sikapnya yang impulsif, energik dan berjiwa pemimpin. \n\n" +
                        "Simbol yang dimiliki oleh zodiak Aries yaitu suatu permulaan baru. Aries menjadi seorang pemimpin untuk jenis zodiak lainnya. Sifatnya yang agresif dan penuh kreativitas membuat mereka berinisiatif mengadakan suatu perubahan. Seperti seekor domba jantan yang bertindak cepat tanpa terlebih dahulu pikir panjang. \n\n" +
                        "Pemilik zodiak ini lebih senang mencari pengakuan dibandingkan mencari kekayaan. Pada umumnya mereka tidak suka berbasa-basi dan lebih suka berbicara secara terus terang untuk memperoleh segala hal yang ingin diketahuinya. \n\n" +
                        "Karena sifat mereka yang pantang menyerah membuat mayoritas dari mereka menjadi orang yang sukses. Aries merupakan individu yang pandai beradaptasi, penuh energi serta cepat belajar. Mereka memiliki banyak sekali ide cemerlang. Ambisi. \n\n" +
                        "Tidak ada siapapun yang bisa menghalanginya jika mereka menginginkan sesuatu hal. Mereka siap mengambil suatu tindakan tanpa melihat bahaya atau resiko yang bisa dialaminya. Aries bukanlah seorang pengikut atau anggota yang bisa dikategorikan baik. \n\n" +
                        "Tetapi, mereka memiliki kemampuan yang biasanya diperlukan untuk menjadi seorang pemimpin yang baik. Namun, sikapnya yang suka sekali memerintah membuat orang lain menjadi menjauhi dirinya."

                },
                {
                        "Taurus",
                        "(21 April – 20 Mei)",
                        "https://moondoggiesmusic.com/wp-content/uploads/2019/06/Zodiak-Taurus-21-April-%E2%80%93-20-Mei.png",
                        "Sapi atau lembu jantan merupakan lambang dari zodiak Taurus. Zodiak ini dimiliki oleh orang yang lahir pada tanggal 21 April sampai 20 Mei. Kategori zodiak ini yaitu statis. Jadi, orang yang mempunyai zodiak Taurus menyukai kemapanan, stabilitas, kesempurnaan, tabah dan daya tahan.\n\n" + "Secara umum sifat pemilik zodiak Taurus menyukai seni, suka traveling, menyukai spiritualitas, loyalitas, tabah, senang berbagi, mengutamakan kekayaan serta kemewahan. Meskipun begitu, orang yang berzodiak Taurus memiliki sifat lebih mengutamakan perasaan mereka sendiri, cenderung keras hati, keras kepala, suka mengatur tetapi tidak suka diatur, sensitif dan juga cenderung materilistis.\n\n" + "Simbol dari Taurus adalah kehendak yang kuat dan kepastian. Untuk memperoleh rasa aman secara jasmani dan rohani mereka mau berjuang. Selera mereka terhadap seni lukisan, pakaian, barang antik serta beragam barang mewah lainnya cukup tinggi. Cita rasa yang dimiliki oleh Taurus sangat tinggi dan juga cenderung konservatif.\n\n" + "Alunan melodi maupun musik yang indah sangat mereka sukai. Mereka suka menolong orang lain, mempunyai jiwa sosial yang tinggi dan tidak mudah marah. Mereka tidak suka didesak dan jika terus menerus didesak akan cenderung menjadi keras kepala. Karakteristik Taurus sabar, stabil dan setia.\n\n" + "Mereka memiliki pandangan yang baik untuk mencapai tujuan yang diinginkan sehingga mereka berhasil meraih tujuan. Terhadap suatu keputusan yang sudah diambil mereka sangat gigih. Tidak ada siapapun yang bisa merubah apa yang diinginkannya atau pendiriannya..\n\n" + "Taurus yang tidak suka didesak membuat banyak orang yang memberikannya julukan si Lamban. Namun, Taurus bisa dipercaya dalam upaya membantu keluar dari masalah yang ada. Mereka tidak mudah melanggar janji dan memiliki stamina serta ketekunan untuk berusaha bertahan dari semua lawan-lawannya."

                },
                {
                        "Gemini",
                        "(21 Mei – 20 Juni)",
                        "https://moondoggiesmusic.com/wp-content/uploads/2019/06/Zodiak-Gemini-21-Mei-%E2%80%93-20-Juni.jpg",
                        "Orang yang mempunyai tanggal lahir 21 Mei sampai tanggal 20 Juni masuk dalam zodiak Gemini dengan lambang berupa anak kembar. Variabel merupakan kategori yang masuk ke dalam zodiak Gemini. Jadi, pada umumnya sifat yang dimiliki oleh orang pemilik zodiak ini adalah ekstrovert atau bersikap terbuka, memiliki kemampuan berbicara, komunikatif, cerdas dan kreatif.\n\n" + "Mereka cenderung tidak bisa diam, suka menulis, supel, suka travelling namun kekanak-anakan. Mereka mudah merasa nerveous, suka bermuka dua dan berbicara omong kosong. Sikap kekanak-kanakkan yang dimiliki oleh Gemini membuatnya tidak kaku dan lincah. Simbol dari Gemini adalah mempunyai banyak akal dan kecerdasan.\n\n" + "Bagi mereka komunikasi sangat berperan penting. Kemampuan belajar dan berkembang yang mereka memiliki tinggi. Biasanya pemilik zodiak ini tidak stabil dan respon terhadap suatu keadaan ditentukan oleh moodnya. Keanekaragaman bagi mereka adalah penyedap yang ada dalam kehidupan.\n\n" + "Mereka bisa menikmati hasil yang mereka raih atas kerja keras mereka sendiri. Rutinitas yang bersifat monoton tidak disukai oleh zodiak Gemini. Mereka memiliki kepandaian yang nampak jelas dan pengetahuan serta pikiran yang cepat.\n\n" + "Simbol dari zodiak ini memiliki pesona yang alami dan karisma yang bisa menarik seluruh zodiak. Banyak ide yang mereka miliki dan bisa membuat orang lain tertarik. Namun, jika berada di sekitar orang yang tidak mampu mengikuti jalan pikiran mereka, mereka cenderung merasa mudah bosan.\n\n" + "Jadi, mereka akan cepat berpindah ke suatu tempat pada lingkungan yang bisa mengikuti jalan pikiran dari mereka. Umumnya mereka menikmati hidup yang mereka jalani dan jarang melihat ke belakang kembali. Pemilik zodiak Gemini dikenal dengan kemampuan mereka bicara tentang segala macam hal dan juga spontanitas.\n\n" + "Mereka energik tetapi memiliki sifat murah hati. Terkadang sikapnya yang tidak konsisten membuat orang lain merasa kesulitan menghadapinya. Apa yang ada di pikirkan pemilik zodiak Gemini dan apa yang akan dilakukannya sulit untuk ditebak."
                },
                {
                        "Cancer",
                        "(21 Juni – 20 Juli)",
                        "https://moondoggiesmusic.com/wp-content/uploads/2019/06/Zodiak-Cancer-21-Juni-%E2%80%93-20-Juli.png",
                        "Tanggal 21 Juni sampai tanggal 20 Juli merupakan kelahiran dari orang yang mempunyai zodiak Cancer. Lambang dari zodiak ini adalah kepiting. Kategori yang masuk dalam zodiak Leo yaitu aktif atau cardinal. Jadi, biasanya orang yang mempunyai zodiak ini bersifat sabar, cerdas, suka menolong, jujur, sensitif, takut akan perpisahan, family man dan mudah bersimpati.\n\n" + "Cancer terkadang juga tidak konsisten, sering merasa tidak aman, senang pura-pura dan defensif. Mereka cenderung sentimentil dan mempunyai suasana hati yang tidak menentu. Namun mereka juga perhatian, setia dan memiliki sifat pemaaf. Daya ingat yang dimilikinya kuat.\n\n" + "Cancer adalah individu yang penuh dengan emosi dan sensitif. Mereka mempunyai pertahanan diri yang tinggi dan sangat protektif seperti seekor kepiting. Mereka takut terhadap cemoohan dan akan bekerja di belakang layar secara diam-diam untuk memperoleh apa yang sudah direncanakan sebelumnya.\n\n" + "Mereka konsisten membayar hutang dan tidak mau mengambil resiko di dalam hidupnya. Cancer mendambakan kebersihan dan kerapian. Cancer juga mempunyai karakter yang sangat simpatik kepada orang lain. Hal itulah yang membuatnya sulit dimengerti sebenarnya seperti apa pribadi mereka.\n\n" + "Cancer mempunyai jiwa intuisi yang kuat dan bisa mengetahui perasaan dari orang-orang yang ditemuinya. Jika ada seseorang yang menantang mereka, mereka bisa menjadi seseorang yang bersifat sangat agresif."

                },
                {
                        "Leo",
                        "(21 Juli – 21 Agustus)",
                        "https://moondoggiesmusic.com/wp-content/uploads/2019/06/Zodiak-Leo-21-Juli-%E2%80%93-21-Agustus.png",
                        "Orang-orang yang mempunyai tanggal kelahiran antara tanggal 21 Juli sampai tanggal 21 Agustus termasuk dalam zodiak Leo. Lambang zodiak Leo yaitu berupa singa dengan planet matahari dan elemen api. Sifat yang dimiliki oleh orang yang berzodiak Leo yaitu ramah, suka traveling, pemurah, senang mengobrol, mempunyai jiwa kepemimpinan, berani, berbakat, suka kemegahan serta keagungan.\n\n" + "Zodiak Leo seringkali bersifat egois, mengejar kemewahan, selalu membanggakan diri, suka pamer dan otoriter. Selain itu mereka mempunyai tingkat kepercayaan diri yang tinggi, stylist, congkak, suka memimpin, murah hati, cukup dermawan serta aristokratik. Leo adalah zodiak yang merupakan anggota kerajaan dari segala jenis zodiak.\n\n" + "Martabat yang mereka miliki tinggi dan juga cenderung sangat dramatis. Selain itu mereka juga penuh warna, sangat gagah dan suka menjadi pusat perhatian. Dalam proses penyusunan suatu organisasi mereka bekerja dengan sangat giat dan mereka juga pandai dalam membagi tugas.\n\n" + "Rencana yang mereka miliki jarang terdengar namun selalu nampak menakjubkan. Mereka cenderung terus terang ketika menyatakan apa yang dirasakan. Namun, terkadang mereka juga mudah marah-marah. Mereka tidak pernah berbuat kecurangan dan memiliki keberanian. Pembawaan diri zodiak Leo begitu mengagumkan.\n\n" + "Jadi, banyak orang yang menjadi tertarik. Leo sangat sulit menyembunyikan perasaan sehingga membuatnya sangat terbuka. Mereka perhatian terhadap segala macam hal dan bisa beradaptasi dengan mudah. Zodiak ini lahir sebagai seorang pemimpin.\n\n" + "Mereka akan merasa sangat kecewa jika tidak mempunyai kekuasaan dalam rangka mendelegasikan tugasnya. Mereka senang hidup seperti anggota kerajaan. Untuk memperoleh gaya hidup yang diinginkan mereka bersedia melakukan segala hal yang dibutuhkan.\n\n" + "Mereka tahu apa yang harus dilakukan secara pasti supaya orang disekitarnya bisa terbujuk untuk melakukan apa yang menjadi kemauannya. Leo sangat gemar melaksanakan segala sesuatu perbuatan yang sifatnya besar. Mereka juga terkenal mempunyai sifat yang dermawan. Dari suatu pertempuran mereka tidak pernah mundur.\n\n" + "Pemilik zodiak ini seringkali membela hak serta kepercayaan yang mereka miliki."
                },
                {
                        "Virgo",
                        "(22 Agustus – 22 September)",
                        "https://moondoggiesmusic.com/wp-content/uploads/2019/06/Zodiak-Virgo-22-Agustus-%E2%80%93-22-September.png",
                        "Tanggal 22 Agustus sampai tanggal 22 September merupakan kelahiran dari orang yang berzodiak Virgo. Simbol atau lambang dari zodiak ini yaitu putri cantik. Elemen yang dimiliki oleh zodiak ini yaitu tanah dan termasuk ke dalam kategori variabel. Jadi sifat orang yang berzodiak Virgo yaitu pekerja keras, simple, perfectionist, senang melayani, fokus pada pekerjaan dan percaya diri.\n\n" + "Meskipun demikian, karakter orang dengan zodiak Virgo berpandangan sempit, dan tidak mau mengalah, kadang senang mengeluh, terlalu kaku, cemas atau khawatir, sering gugup dan senang mengkritik. Cara berpikir zodiak ini praktis, kritis, analistis, namun cenderung dingin, keras kepala serta logis.\n\n" + "Virgo merupakan sosok penganalisa serta pengurus organisasi yang baik. Mereka ingin segala sesuatu yang dikerjakan bisa berhasil dengan baik dan juga sempurna. Mereka ingin senantiasa memperoleh perhatian dari lingkungan sekelilingnya karena kesempurnaan dan juga efisiensinya.\n\n" + "Sikap suka mengkritik hasil kerja orang lain yang dimiliki oleh Virgo seringkali membuat orang lain tidak menyukainya. Virgo suka dengan masakan yang lezat dan mengagumi perkembangan teknologi. Ketangkasan serta kemampuan dalam mengkoordinasi sesuatu tingkatannya melebihi rata-rata.\n\n" + "Sikapnya biasanya penuh dengan emosi. Virgo selalu tampil dengan wangi, rapi dan bersih. Mereka memiliki cita rasa yang tinggi namun cenderung bersifat konservatif. Mereka pandai dalam mengatur orang lain namun begitu ia tidak menyukai seseorang, maka sikapnya akan menjadi sombong.\n\n" + "Mereka bisa menyelesaikan masalah dengan cepat dan berakal panjang. Sifat perfeksionis yang dimiliki oleh Virgo membuat orang yang ada disekelilingnya menjadi merasa risih. Jika segala sesuatu yang diinginkannya tidak berjalan seperti dengan yang diharapkan, maka ia akan menjadi marah.\n\n" + "Namun, untuk menolong orang lain yang memerlukan bantuan mereka selalu bersedia."
                },
                {
                        "Libra",
                        "(23 September – 22 Oktober)",
                        "https://moondoggiesmusic.com/wp-content/uploads/2019/06/Zodiak-Libra-23-September-%E2%80%93-22-Oktober.png",
                        "Neraca atau timbangan adalah lambang dari zodiak Libra. Zodiak ini masuk dalam jenis kardinal aktif. Orang yang berzodiak Libra adalah mereka yang lahir tanggal 23 September sampai tanggal 22 Oktober. Secara umum pemilik zodiak libra menyukai keseimbangan, mengutamakan kesetaraan, harmonisasi, senang beraliansi, suka keadilan, family man, suka hal-hal yang berbau seni, ceria, senang menolong serta pandai berdiplomasi.\n\n" + "Terkadang Libra suka berpura-pura, tidak jujur serta kurang terencana. Mereka penuh dengan keraguan, bermuka dua, agak bimbang, memiliki naluri yang kuat dan mempesona. Mereka nampak cukup menawan, mempunyai inteligensi di atas rata-rata dan sulit untuk ditebak.\n\n" + "Libra mampu bekerja sama dan adil, namun selalu mencari ketenangan batin karena penuh dengan kebimbangan. Mereka selalu melakukan apapun untuk memenuhi segala kebutuhannya dan selalu merasa khawatir terhadap hari ini. Daripada bekerja sendiri mereka lebih menyukai bekerja sama.\n\n" + "Mereka mempunyai minat yang besar terhadap pengetahuan dan terhadap bidang kejiwaan serta kehumasan. Mereka jarang marah dan senantiasa tampil sebagai pembawa damai. Jika marah Libra bisa membuat orang yang ada di sekitarnya merasa ketakutan.\n\n" + "Cita rasa yang dimiliki oleh Libra mudah ditebak. Mereka menyukai gabungan antara kesempurnaan dengan kesederhanaan. Bagi mereka langkah mundur yang paling besar yaitu sebuah keragu-raguan. Hal ini membuat siapa saja yang berhubungan dengan Libra menjadi merasa bingung dan mereka juga kehilangan kesempatan. Libra bersedia untuk berkorban.\n\n" + "Mereka memiliki jiwa seni, rencana dan estetika. Itulah yang nantinya akan membantu Libra untuk meraih apa yang sudah mereka tetapkan. Libra selalu sukses di dalam proses menyelesaikan tugasnya. Hal ini karena mereka mampu membujuk orang lain supaya melaksanakan sesuatu hal seperti yang diinginkannya."
                },
                {
                        "Scorpio",
                        "(23 Oktober – 22 November)",
                        "https://moondoggiesmusic.com/wp-content/uploads/2019/06/Zodiak-Scorpio-23-Oktober-%E2%80%93-22-November.png",
                        "Orang yang lahir pada tanggal 23 Oktober sampai tanggal 22 November mempunyai zodiak jenis Scorpio. Simbol dari zodiak ini yaitu berupa kalajengking yang memiliki elemen air. Kategori zodiak Scorpio adalah statis. Jadi, karakter yang dihasilkan yaitu meliputi suka dengan kemewahan, kreatif, stamina tinggi, mempunyai keinginan yang kuat dan senang membantu orang lain.\n\n" + "Scorpio juga fanatik, pencemburu, senang menyerang, agak tamak, ekstrim dan suka menuntut. Scorpio cenderung pendiam, sangat banyak akal serta pendendam. Selain itu mereka sangat gigih dan juga tekun. Pemilik zodiak ini merupakan orang yang cukup posesif, emosional dan giat.\n\n" + "Tatapan matanya merupakan daya tarik yang bisa menarik orang lain. Scorpio bisa menjadi individu yang setia, namun juga menjadi seorang musuh yang berbahaya. Pribadi mereka penuh dengan etika. Selain itu juga berpegang teguh terhadap berbagai macam peraturan yang mereka yakini.\n\n" + "Karakter penolong dan setia yang dimilikinya membuat setiap orang yang mengenalnya merasa beruntung ada di pihaknya. Scorpio bisa menjadi seorang musuh yang pendendam dan cenderung sangat kejam jika ada di pihak yang berlawanan terhadapnya. Orang-orang yang bisa mengetahui kemampuan dari Scorpio hanyalah sedikit.\n\n" + "Hal ini karena sikapnya yang rendah hati terhadap apa saja yang sudah diraihnya dan pendiam. Mereka jarang menarik kembali kata-kata yang telah diucapkannya dan merupakan orang yang senantiasa menepati janji. Mereka pandai dalam mengukur keadaan dan merupakan seorang pengamat yang cermat.\n\n" + "Mereka tidak pernah ikut andil dalam keadaan tanpa suatu persiapan yang matang. Hal inilah yang membuat Scorpio menjadi seorang pesaing yang tangguh. Mereka penuh informasi, senantiasa bersedia menolong yang lemah serta sangat pandai dalam menjaga rahasia."
                },
                {
                        "Sagitarius",
                        "(23 November – 20 Desember)",
                        "https://moondoggiesmusic.com/wp-content/uploads/2019/06/Zodiak-Sagitarius-23-November-%E2%80%93-20-Desember.png",
                        "Tanggal 23 November sampai tanggal 20 Desember merupakan kelahiran dari orang yang mempunyai zodiak Sagitarius. Elemen zodiak ini adalah api. Sedangkan kategori variabelnya cenderung dinamis. Jadi, beberapa sifat yang dimilikinya yaitu mempunyai tekat yang kuat, bijaksana, sangat optimis, gemar belajar, suka tantangan, suka melakukan eksplorasi terhadap hal baru serta percaya diri.\n\n" + "Selain itu, Sagitarius merupakan pribadi yang religius, mudah lalai, boros, gelisah, lebih mengutamakan apa yang dikatakan oleh hati, berbelas kasih serta kurang bertanggung jawab. Pemilik zodiak Sagitarius merupakan individu yang jujur, pandai dalam membawa diri, energik dan terus terang.\n\n" + "Mereka bisa mencapai suatu tujuan karena mempunyai pikiran yang positif.  Meskipun demikian ide-ide yang mereka miliki cenderung sering sulit untuk dimengerti. Mereka seringkali mengambil suatu kesimpulan tanpa terlebih dahulu mengumpulkan fakta. Wawasan yang mereka miliki luas, diplomatis dan juga fleksibel.\n\n" + "Keinginannya untuk berpetualang membawa ia ke berbagai macam tempat yang jauh. Sagitarius bisa menjadi salah satu teman perjalanan yang begitu menyenangkan. Hal ini karena mereka pandai dalam beradaptasi terhadap lingkungan yang ada di sekitarnya.\n\n" + "Sagitarius juga mandiri. Sebagai teman seperjalanan, mereka sangat menyenangkan dan penuh pesona. Mereka tidak akan pernah menyesali jika uang sakunya sudah habis. Sebab mereka merasa menikmati dengan apa yang sudah mereka peroleh. Sagitarius adalah sosok pemula yang pandai dalam membawa diri dan selalu bersedia menolong orang lain yang membutuhkan bantuan.\n\n" + "Antusiasme yang ada pada pribadi mereka membuat orang lain bisa terinspirasi. Mereka mudah sekali terkenal atau tenar. Kemampuan dalam hal perencanaan mereka jika digabungkan dengan stamina dan etika kerja yang kuat bisa membuat mereka menjadi pemenang.\n\n" + "Mereka mudah memperoleh dukungan dari orang lain karena sikapnya yang persuasif. Karakteristik lainnya dari zodiak Sagitarius adalah materialis, tetapi tidak suka hidup yang berlebih-lebihan. Jiwa yang dimiliki oleh Sagitarius bebas, mempunyai banyak teman dan merupakan individu yang menyenangkan.\n\n" + "Itulah uraian mengenai karakteristik dari masing-masing zodiak. Jadi, apapun jenis zodiak yang Anda miliki, semuanya ada sisi positif dan negatifnya. Semuanya memiliki kekurangan dan kelebihannya sendiri-sendiri. Sehingga, sebaiknya kita bisa menyeimbangkan apa yang ada pada diri kita."
                }
        };

        public static ArrayList<Zodiak> getData() {
            ArrayList<Zodiak> list = new ArrayList<>();
            for (String[] item : data) {
                Zodiak zodiak = new Zodiak();
                zodiak.setName(item[0]);
                zodiak.setOrigin(item[1]);
                zodiak.setPhoto(item[2]);
                zodiak.setDescription(item[3]);

                list.add(zodiak);
            }

            return list;
        }
}